### ISSUE TITLE
Update for react-navigation@5

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/search-layout#12]

**Comment by summerkiflain** [comment]
@brentvatne is it possible?

**Comment by armenio** [comment]
> @brentvatne is it possible?

https://github.com/react-navigation/search-layout/pull/20

**Comment by summerkiflain** [comment]
@brentvatne can you please publish this on npm also?

**Comment by brentvatne** [comment]
@summerkiflain - it looks like @eriveltonelias is planning on doing this, i don't want to interfere with his plans

https://github.com/react-navigation/search-layout/pull/20#pullrequestreview-546131806

**Comment by eriveltonelias** [comment]
thanks @brentvatne ❤️ I'm your biggest fan haha

I'll just do some cleanup and publish it.
