### ISSUE TITLE
Package has no peerDependencies defined.

### ISSUE THREAD

**Issue by brunokiafuka** [react-navigation/search-layout#19]
I've added the search-layout add on into a bare Expo project and I have to be installing its dependencies manually. 

Shouldn't the package come with the packages that it depends on already set? or these dependencies (i.e: `react-native-safe-area-view`) are expected to be already set it up by the dev when using `react-navigation`. 

Best 🚀

**Comment by summerkiflain** [comment]
@brentvatne can't we remove the `react-native-safe-area-view` dependency and shift to `react-native-safe-area-context` altogether, there are 3 versions of `react-native-safe-area-view` on npm, `default`, `latest` & `next`, and I couldn't find below imports in any version of the package.
```
import { getInset, getStatusBarHeight } from 'react-native-safe-area-view';
```
This always goes into 2nd condition and picks the statusBar height from react-native import.
```
const ANDROID_STATUS_BAR_HEIGHT = getStatusBarHeight
      ? getStatusBarHeight()
      : StatusBar.currentHeight;
```
I am using a non-translucent status bar in my expo managed-flow app and its adding additional top padding in android version of the app. I am using `yarn patch-package` to change `ANDROID_STATUS_BAR_HEIGHT` to zero for that.

**Comment by brentvatne** [comment]
hi @summerkiflain - that's a good call! do you want to help out with maintaining this project? i do not have time to maintain it and @eriveltonelias is also relatively busy as i understand

**Comment by summerkiflain** [comment]
@brentvatne sure, I can manage that for now.

**Comment by brentvatne** [comment]
@summerkiflain - i have added you as a collaborator
