### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by MoathOthman** [react-navigation/search-layout#8]
Hey , thnx for the library 

after following the readme and running the app with search layout am getting this 

```
/Users/path../node_modules/react-navigation-addon-search-layout/index.js 1:20
Module parse failed: Unexpected token (1:20)
You may need an appropriate loader to handle this file type.
> export default from "./src/SearchLayout";
```
this error won't stop the app from running or functioning probably on mobile (though i get the error on the logs),
but it will stop it if i run the app with 
`expo start --web` 

Regards,

**Comment by brentvatne** [comment]
it wasn't made to support web but we should add this. tracking in https://github.com/react-navigation/search-layout/issues/13
